name: setup-workflow
permissions:
  contents: read
runs:
  using: "composite"
  name: Setup dependencies
  runs-on: ubuntu-22.04
  steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libharfbuzz-dev
            libfribidi-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
